version: '3'

services:

  gateway: 
    build:
      context: .
      dockerfile: Dockerfile.gateway
    depends_on:
      - data
      - user
    ports:
      - '23000:23000'

  data: 
    build:
      context: .
      dockerfile: Dockerfile.data
    depends_on:
      postgres:
        condition: service_healthy

  user: 
    build:
      context: .
      dockerfile: Dockerfile.user
    depends_on:
      postgres:
        condition: service_healthy

  postgres: 
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: pass

    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U  postgres -d postgres'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s 
