version: '3'

services:
  
  webservice: 
    build:      # . -> the following two lines are redundant but help me understand a bit better the potential properties that I could use
      context: .
      dockerfile: Dockerfile 
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '23000:23000'

  postgres: 
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U  postgres -d postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 
